name: the organization required workflow

on: pull_request_target

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Echo greeting
        run: echo "hello organization from the required workflow"
