name: resuable_with_two_jobs

on:
  workflow_call:
    outputs:
      first:
        value: ${{ jobs.job-a.outputs.output-a }}
      second:
        value: ${{ jobs.job-a.outputs.output-b }}
      third:
        value: ${{ jobs.job-b.outputs.output-c }}

jobs:
  job-a:
    runs-on: ubuntu-latest
    outputs:
      output-a: ${{ steps.step1.outputs.role }}
      output-b: ${{ steps.step2.outputs.foo }}
    steps:
      - id: step1
        run: echo "role=admin" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "foo=bar" >> $GITHUB_OUTPUT
  job-b:
    runs-on:
      ubuntu-latest
    outputs:
      output-c: ${{ steps.step1.outputs.path }}
    steps:
      - id: step1
        run: echo "path=failure" >> $GITHUB_OUTPUT
