# This workflow is called from another workflow

name: SayHello

on:
  workflow_call:
    inputs:
      employee-name:
        required: true
        type: string
    secrets:
      access_token:
        required: true
      

jobs:
  reusable_job:

    runs-on: ubuntu-latest
    
    steps:
    - name: Echo Hello Message
      run: echo ${{ inputs.employee-name }}
      
  #  - name: Echo PIN
  #    run: echo ${{ secrets.pin }}
      
    - name: if pin equals 9999
      env:
        MY_PIN: ${{ secrets.access-token }}
      if: env.MY_PIN == 9999
      run: echo "The pin is what u thought which is 9 9 9   9"
